apiVersion: v1
kind: Pod
metadata:
  name: vaultwarden-restore
  namespace: vaultwarden
spec:
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  nodeSelector:
    kubernetes.io/hostname: k3s-node-0
  containers:
  - name: restore
    image: ubuntu:24.04
    command: ["/bin/bash", "-c", "sleep 3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: vaultwarden-data-pvc
